# See repositories to check each declared pre-commit hook
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # work around custom yaml syntax of !reference in gitlab ci
      - id: check-yaml
        name: Check YAML (unsafe)
        args: [ --unsafe ]
        files: .gitlab-ci.yml
      # check other yaml files normally
      - id: check-yaml
        exclude: .gitlab-ci.yml

      - id: check-added-large-files
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
